"""
0006_create_teacher_account.py
Migration to create a default teacher account if it doesn't exist.
Generated by Django 5.2.6
"""

from django.db import migrations

# Function to create a default teacher account
def create_teacher_account(apps, schema_editor):
    Student = apps.get_model('lms', 'Student')
    if not Student.objects.filter(Email='Teacher@gmail.com').exists():
        Student.objects.create(
            Name='Teacher',
            Email='Teacher@gmail.com',
            Password='Teaching123!',
            Role='teacher',
            Enrollments=''  # No enrollments for teacher
        )

class Migration(migrations.Migration):
    dependencies = [
        ('lms', '0005_alter_student_name'),
    ]
    operations = [
        migrations.RunPython(create_teacher_account),
    ]
