# Generated by Django 5.2.6 on 2025-09-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseID', models.AutoField(db_column='CourseID', primary_key=True, serialize=False)),
                ('Title', models.CharField(db_column='Title', max_length=255)),
                ('Description', models.TextField(blank=True, db_column='Description', null=True)),
            ],
            options={
                'db_table': 'courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('Role', models.CharField(default='student', max_length=32)),
                ('Enrollments', models.CharField(blank=True, default='', max_length=1024)),
            ],
            options={
                'db_table': 'students',
                'managed': True,
            },
        ),
    ]
