"""
0002_student_email.py
Migration to add Email field to Student model.
Generated by Django 5.2.6 on 2025-09-18 07:29
"""

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        # Add Email field to Student
        migrations.AddField(
            model_name='student',
            name='Email',
            field=models.EmailField(default='unknown@example.com', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
