# Generated by Django 5.2.6 on 2025-09-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Email',
            field=models.EmailField(max_length=255),
        ),
    ]
