"""
0004_alter_student_email.py
Migration to alter Student Email field (add unique constraint back).
Generated by Django 5.2.6 on 2025-09-18 08:20
"""

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_student_email'),
    ]

    operations = [
        # Alter Email field (add unique constraint back)
        migrations.AlterField(
            model_name='student',
            name='Email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
