"""
0005_alter_student_name.py
Migration to alter Student Name field (remove unique constraint).
Generated by Django 5.2.6 on 2025-09-18 10:05
"""

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_alter_student_email'),
    ]

    operations = [
        # Alter Name field (remove unique constraint)
        migrations.AlterField(
            model_name='student',
            name='Name',
            field=models.CharField(max_length=255),
        ),
    ]
