# Generated by Django 5.2.6 on 2025-09-30 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_create_teacher_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'managed': True},
        ),
    ]
